name: Build and Test

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'v*'
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: apt
      run: sudo apt-get install gcc autoconf bison gettext autopoint help2man lzip texinfo texlive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: print generated man page (raw)
      run: |
        ( cd doc && ../src/flex --help )
        ( cd doc && ../src/flex --version )
        ls -l doc/flex.1
        cat doc/flex.1

  cross-build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: apt
      run: sudo apt-get install gcc autoconf bison gettext autopoint help2man lzip texinfo texlive gcc-aarch64-linux-gnu
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --build=x86_64-linux-gnu --host=aarch64-linux-gnu
    - name: make
      run: make
    - name: print generated man page (raw)
      run: |
        ( cd doc && ../src/stage1flex --help )
        ( cd doc && ../src/stage1flex --version )
        ls -l doc/flex.1
        cat doc/flex.1
